name: Build - Action bundle
on:
  push:
    paths:
      - src/**
      - package-lock.json
      - tsconfig.json
      - test/**
    branches-ignore:
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    # Exclude in-repo PRs from running this job
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Install npm development dependencies
        run: npm install
      - name: Build action
        run: npm run build
      - name: Commit and push action bundle
        uses: EndBug/add-and-commit@v9
        with:
          add: -f dist/main/index.js dist/cleanup_working_directory/index.js
          message: 'chore(dist): build'
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
