name: Static analysis - Check format and run linter
on:
  push:
    paths:
      - src/**
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  format:
    runs-on: ubuntu-latest

    # Exclude in-repo PRs from running this job
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork

    steps:
      - name: Clone repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup Node.js 16
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version: 16.x
          cache: npm
      - name: Install npm development dependencies
        run: npm install
      - name: Check format
        run: npm run format-check
      - name: Run ESLint
        run: npm run lint
