name: Static analysis - Check format and run linter
on:
  push:
    paths:
      - src/**
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  format:
    runs-on: ubuntu-latest

    # Only run if this is not a pull request, or for pull requests on forks
    if: github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name != 'ComunidadAylas/PackSquash-action'

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Install npm development dependencies
        run: npm install
      - name: Check format
        run: npm run format-check
      - name: Run ESLint
        run: npm run lint
