name: Static analysis - Check format and run linter
on:
  push:
    paths:
      - src/**
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  format:
    runs-on: ubuntu-latest

    # Exclude in-repo PRs from running this job
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork

    steps:
      - name: Clone repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - name: Setup Node.js 16
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 16.x
          cache: npm
      - name: Install npm development dependencies
        run: npm install
      - name: Check format
        run: npm run format-check
      - name: Run ESLint
        run: npm run lint
