name: Static analysis - Check format and run linter
on:
  push:
    paths:
      - src/**
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  format:
    runs-on: ubuntu-latest

    # Exclude in-repo PRs from running this job
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork

    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Node.js 20
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install npm development dependencies
        run: npm ci
      - name: Check format
        run: npm run format-check
      - name: Run ESLint
        run: npm run lint
