name: Test - Pack in submodule
on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest

    # Only run if this is not a pull request, or for pull requests on forks
    if: github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name != 'ComunidadAylas/PackSquash-action'

    steps:
      - name: Clone pack repository
        uses: actions/checkout@v3
        with:
          repository: ComunidadAylas/PackSquash-action-test
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clone action repository
        uses: actions/checkout@v3
        with:
          path: action-checkout
      - name: Modify pack files
        run: |
          echo '{ "pack": { "pack_format": 8, "description": "Dummy pack.mcmeta" } }' > golden-days/golden-days-base/pack.mcmeta
          touch golden-days/golden-days-base/assets/minecraft/sounds.json
          rm golden-days/golden-days-base/pack.png
          mv golden-days/golden-days-base/credits.txt golden-days/golden-days-base/credits_new.txt
      - name: Run PackSquash
        uses: ./action-checkout
        with:
          path: golden-days/golden-days-base
