name: Test - Windows runner
on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
jobs:
  test:
    runs-on: windows-latest

    # Exclude in-repo PRs from running this job
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork

    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Run PackSquash
        uses: ./ # Uses an action in the root directory
        with:
          packsquash_version: latest
          options: |
            pack_directory = 'test/empty_resource_pack'
