name: Test - Pack submodule
on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest

    # Exclude in-repo PRs from running this job
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork

    steps:
      - name: Clone pack repository
        uses: actions/checkout@v3
        with:
          repository: ComunidadAylas/PackSquash-action-test
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clone action repository
        uses: actions/checkout@v3
        with:
          path: action-checkout
      - name: Run PackSquash
        uses: ./action-checkout
        with:
          packsquash_version: latest
          options: |
            pack_directory = 'Programmer-Art-Plus'
