name: Test - Pack in submodule
on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest

    # Exclude in-repo PRs from running this job
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork

    steps:
      - name: Clone action repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          path: action
      - name: Set up empty Git repository with public pack submodules
        uses: ./action/.github/workflows/actions/set_up_repo_with_submodules
      - name: Modify pack files (test that working directory changes are handled well)
        run: |
          touch golden-days/golden-days-base/assets/minecraft/sounds.json
          printf ' ' >> golden-days/golden-days-base/assets/minecraft/models/block/acacia_leaves.json
          sed -i 's/:/ :/g' golden-days/golden-days-base/assets/minecraft/models/block/acacia_log.json
          mv golden-days/golden-days-base/credits.txt golden-days/golden-days-base/credits_new.txt
          rm golden-days/golden-days-base/assets/minecraft/optifine/color.properties
      - name: Run PackSquash
        uses: ./action
        env:
          PACKSQUASH_ACTION_EXTRA_VERBOSE_FILE_TIMES_LOGGING: 1
        with:
          packsquash_version: latest
          options: |
            pack_directory = 'golden-days/golden-days-base'

            ['**/*.png']
            maximum_width_and_height = 65535
