name: Test - Pack in submodule
on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest

    # Exclude in-repo PRs from running this job
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork

    steps:
      - name: Clone pack repository
        uses: actions/checkout@v3
        with:
          repository: ComunidadAylas/PackSquash-action-test
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clone action repository
        uses: actions/checkout@v3
        with:
          path: action-checkout
      - name: Modify pack files
        run: |
          echo '{ "pack": { "pack_format": 8, "description": "Dummy pack.mcmeta" } }' > golden-days/golden-days-base/pack.mcmeta
          touch golden-days/golden-days-base/assets/minecraft/sounds.json
          mv golden-days/golden-days-base/credits.txt golden-days/golden-days-base/credits_new.txt
          # Remove some files that generate GStreamer negotiation errors on v0.3.1.
          # This also serves to check that the action handles files being deleted from the working copy correctly
          rm golden-days/golden-days-base/assets/minecraft/sounds/liquid/*.ogg
      - name: Run PackSquash
        uses: ./action-checkout
        with:
          path: golden-days/golden-days-base
          maximum_image_width_and_height: 65535
