name: Test - Empty resource pack
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path: test/empty_resource_pack
