name: Test - EmptyResourcePack
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Cache PackSquash
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-packsquash-${{ env.cache-name }}-${{ hashFiles('test') }}
          restore-keys: |
            ${{ runner.os }}-packsquash-${{ env.cache-name }}-
          path: |
            packsquash_cache
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@master
        with:
          path: test/empty-resource-pack
          zip_spec_conformance_level: high
          output_path: test/empty-resource-pack.zip
      - name: Upload Optimized Pack
        uses: actions/upload-artifact@v2
        with:
          name: empty-resource-pack.zip
          path: test/empty-resource-pack.zip