name: Test - Run in multiple steps
on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest

    # Exclude in-repo PRs from running this job
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run PackSquash
        uses: ./ # Uses an action in the root directory
        with:
          path: test/empty_resource_pack
          artifact_name: 'Optimized pack 1'
      - name: Run PackSquash
        uses: ./
        with:
          path: test/empty_resource_pack
          artifact_name: 'Optimized pack 2'
